apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
spec:
  serviceName: worker
  replicas: 2 # Adjust this number to change the number of worker pods
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 10000Mi
        - name: gskey
          secret:
            secretName: storage-auth #kubectl create secret generic storage-auth --from-file=gskey.json=./gskey.json
      containers:
        - name: worker
          image: yesq/scripts # Replace with your worker image
          command: ["/worker.sh"] # Replace with your command
          workingDir: /workdir
          env:
            - name: PROJECT_ID
              value: "my-project"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PASSWORD
              value: "YourSecurePassword"
          volumeMounts:
            - mountPath: /workdir
              name: cache-volume
            - name: gskey
              mountPath: /gskey/
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
